sets.exported={
    main={ name="Espiritus", augments={'Summoning magic skill +15','Pet: Mag. Acc.+30','Pet: Damage taken -4%',}},
    sub="Elan Strap",
    ammo="Sancus Sachet",
    head="Con. Horn +1",
    body="Con. Doublet +1",
    hands="Lamassu Mitts",
    legs={ name="Enticer's Pants", augments={'MP+40','Pet: Mag. Acc.+9','Pet: Damage taken -2%',}},
    feet="Con. Pigaches +1",
    neck="Adad Amulet",
    waist="Lucidity Sash",
    left_ear="Esper Earring",
    right_ear="Lugalbanda Earring",
    left_ring="Varar Ring",
    right_ring="Varar Ring",
    back={ name="Campestres's Cape", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Eva.+20 /Mag. Eva.+20',}},
}