sets.exported={
    main="Naegling",
    sub="Kaja Rod",
    ammo="Mavi Tathlum",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Hashi. Bazu. +1",
    legs={ name="Luhlaza Shalwar +3", augments={'Enhances "Assimilation" effect',}},
    feet="Jhakri Pigaches +2",
    neck={ name="Mirage Stole +2", augments={'Path: A',}},
    waist={ name="Acuity Belt +1", augments={'Path: A',}},
    left_ear="Njordr Earring",
    right_ear="Hermetic Earring",
    left_ring="Kishar Ring",
    right_ring="Ayanmo Ring",
    back={ name="Cornflower Cape", augments={'MP+22','DEX+5','Blue Magic skill +10',}},
}